Fixed underestimated therapeutic coverage bug
ChangePlusPlusVandy/UFAR-backend pull request #41
Opened 2022-05-12 04:30 UTC by carolhe134

Closes #39

2022-05-13 07:17 UTC, salomondush commented
Hi @carolhe134, I forgot to also mention that the numerator should also be the total number of children (aged 5-14) treated, NOT all persons. Using all persons would make the numerator bigger than the denominator at some point.  

Refer to the screenshots below. It's completely my bad - I should've clarified. 

<img width="809" alt="Screen Shot 2022-05-13 at 2 13 32 AM" src="https://user-images.githubusercontent.com/63796975/168231184-5eb48d21-1055-40c8-a2be-8e52dbc7644d.png">

<img width="813" alt="Screen Shot 2022-05-13 at 2 13 11 AM" src="https://user-images.githubusercontent.com/63796975/168231225-3e4852e3-5f61-4836-b851-169d22fdbb5e.png">

2022-05-13 07:18 UTC, salomondush requested changes
Look at the comments and screenshots I left on the conversations.

2022-05-13 14:40 UTC, carolhe134 commented
It's ok! I already accounted for that.
![Screenshot 2022-05-13 093947](https://user-images.githubusercontent.com/89999830/168307682-cdd6f283-d68c-4917-b4f3-7ac9b3a243ae.png)

2022-05-14 01:07 UTC, salomondush approved these changes

2022-05-14 01:08 UTC, merged